# version: '3'

# services: 
#   dog-server:
#     image: nginx
#     container_name: 'dog-container'
#     volumes: 
#       - ./dog-server:usr/share/nginx/html
#     ports:
#       - 7000:80

#     cat-server:
#       image: nginx
#       container_name: 'cat-container'
#       volumes: 
#         - ./cat-server:usr/share/nginx/html
#       ports:
#         - 7001:80

#     reverse-proxy: 
#       image: nginx
#       volumes: 
#         - ./proxy/nginx.conf:/etc/nginx/nginx.conf
#       ports: 
#         - 80:80

version: '3'

services:
  dog-server:
    image: nginx
    container_name: 'dog-container'
    volumes:
      - ./dog-server:/usr/share/nginx/html
    expose:
      - "80"

  cat-server:
    image: nginx
    container_name: 'cat-container'
    volumes:
      - ./cat-server:/usr/share/nginx/html
    expose:
      - "80"

  reverse-proxy:
    image: nginx
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"